# Generated by Django 2.1.4 on 2020-03-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookborrow',
            fields=[
                ('brid', models.CharField(db_column='brid', default='', max_length=15, primary_key=True, serialize=False)),
                ('rid', models.CharField(db_column='rid', max_length=30, null=True)),
                ('bbid', models.CharField(db_column='bbid', max_length=30, null=True)),
                ('brrowdate', models.CharField(db_column='brrowdate', max_length=30, null=True)),
                ('returndate', models.CharField(db_column='returndate', max_length=12, null=True)),
            ],
            options={
                'db_table': 'bookborrow',
                'managed': True,
            },
        ),
    ]
