# Generated by Django 2.1.4 on 2020-03-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='onebook',
            fields=[
                ('bbid', models.CharField(db_column='bbid', default='', max_length=15, primary_key=True, serialize=False)),
                ('bid', models.CharField(db_column='bid', max_length=30, null=True)),
                ('sheft', models.CharField(db_column='sheft', max_length=60, null=True)),
                ('place', models.CharField(db_column='place', max_length=60, null=True)),
                ('state', models.CharField(db_column='state', max_length=20, null=True)),
            ],
            options={
                'db_table': 'onebook',
                'managed': True,
            },
        ),
    ]
