# Generated by Django 2.1.4 on 2020-03-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onebook',
            name='state',
        ),
        migrations.AddField(
            model_name='onebook',
            name='statu',
            field=models.CharField(db_column='statu', max_length=20, null=True),
        ),
    ]
