# Generated by Django 2.1.4 on 2020-04-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookborrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='bbid',
            field=models.CharField(db_column='bbid', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='rid',
            field=models.CharField(db_column='rid', default='', max_length=30),
        ),
    ]
