# Generated by Django 2.1.4 on 2020-04-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='aname',
            field=models.CharField(db_column='aname', default='', max_length=6),
        ),
    ]
