# Generated by Django 2.1.4 on 2020-03-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('aid', models.CharField(db_column='aid', default='', max_length=10, primary_key=True, serialize=False)),
                ('apsd', models.CharField(db_column='apsd', max_length=6, null=True)),
                ('aname', models.CharField(db_column='aname', max_length=6, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
    ]
